# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        CoreBundle\Entity\Usuarios:
            algorithm: plaintext

        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
        # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [user_db]
        in_memory:
            memory: ~
        user_db:
            entity: { class: CoreBundle\Entity\Usuarios }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            provider: user_db
            logout:
                 path:   /logout
                 target: index
            form_login:
                login_path: login
                check_path: login
                default_target_path: index
                always_use_default_target_path: true
                target_path_parameter: index
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html